# -*- coding: utf-8 -*-
"""Bond Equivalent Yield (BEY) Method.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GY4hkAbU0sDpxBqHoxiTXz6g90n5yNpp

The bond equivalent yield (BEY) method is a popular method for calculating the yield on a bond. It is commonly used to calculate the yield on short-term bonds that have a maturity of less than one year.

The BEY is a simple annualized yield that assumes a 365-day year and semi-annual compounding. It is calculated by multiplying the semi-annual yield by two.

To calculate the price of a bond using the BEY method, we need to first calculate the semi-annual yield and then convert it to the BEY. We can then use the BEY to calculate the price of the bond using the following formula:

Bond Price = (Annual Interest Payment / BEY) x (1 - 1 / (1 + BEY / 2)^(2 x N))

where:

Annual Interest Payment: the annual interest payment on the bond
BEY: the bond equivalent yield
N: the number of semi-annual periods until maturity
Here's the Python code to calculate the price of a bond using the BEY method:
"""

# Input variables
par_value = 1000
coupon_rate = 0.06
semi_annual_coupon = par_value * coupon_rate / 2
semi_annual_yield = 0.04
n_periods = 4

# Calculate BEY
bey = semi_annual_yield * 2

# Calculate bond price
bond_price = (semi_annual_coupon / bey) * (1 - 1 / (1 + bey / 2) ** (2 * n_periods)) + par_value / (1 + bey / 2) ** (2 * n_periods)

print("Bond price using BEY method: ${:.2f}".format(bond_price))

"""In this example, we have a bond with a par value of $1,000, a coupon rate of 6%, and a maturity of 1 year (2 semi-annual periods). The semi-annual coupon is calculated as $30 ($1,000 * 6% / 2), and the semi-annual yield is assumed to be 4%.

We then calculate the BEY by multiplying the semi-annual yield by 2, which gives us 8%. We use the BEY to calculate the bond price using the formula above, which gives us a bond price of $1,015.60.

# More about the model:

The Bond Equivalent Yield (BEY) method is a way to calculate the annualized yield on a discounted security such as a U.S. Treasury bill or a commercial paper. This method is used to compare the yields of securities with different maturities and discount rates.

The BEY is calculated by doubling the semiannual yield, which is the yield on the security assuming it pays interest twice a year. This is done because most bonds and other fixed-income securities make semiannual interest payments. By doubling the semiannual yield, the BEY represents the yield over a full year, making it easier to compare the yields of securities with different payment frequencies.

The formula for calculating the BEY is:

BEY = (face value - purchase price) / (purchase price x (days to maturity / 365)) x 100

where face value is the amount the bond will be worth at maturity, purchase price is the price paid for the bond, and days to maturity is the number of days until the bond matures.

For example, if an investor purchases a $10,000 U.S. Treasury bill with 90 days to maturity for $9,900, the BEY would be:

BEY = ($10,000 - $9,900) / ($9,900 x (90 / 365)) x 100
BEY = 4.04%

This means that the investor will earn an annualized yield of 4.04% on the Treasury bill. By using the BEY method, investors can compare the yields of securities with different maturities and discount rates and make informed investment decisions.
"""