# -*- coding: utf-8 -*-
"""Relative Value Method.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18OGelukQ_9Ty_F-2RVwk_9wKEt4iT-ga

The Relative Value Method (RVM) is a bond pricing method that compares the yields of different bonds with similar characteristics to determine the relative value of a specific bond. It assumes that similar bonds should have similar yields, and any differences in yields between similar bonds can be attributed to differences in credit quality or other factors.

To price a bond using RVM, we need to find comparable bonds and calculate their yields. We can then use these yields to estimate the yield for the bond we want to price. Here's the Python code to implement the RVM bond pricing method:
"""

# Import necessary libraries
import pandas as pd

# Define bond parameters
face_value = 1000
coupon_rate = 0.06
years_to_maturity = 5
current_price = 950

# Define comparable bonds
bonds = pd.DataFrame({
    'Coupon': [0.05, 0.07, 0.06],
    'Years to Maturity': [5, 5, 5],
    'Price': [980, 930, 960]
})

# Calculate the yields of comparable bonds
bonds['Yield'] = [((face_value * coupon) + (face_value - bond_price)) / (face_value * years)
                  for coupon, bond_price, years in zip(bonds['Coupon'], bonds['Price'], bonds['Years to Maturity'])]

# Calculate the average yield of comparable bonds
avg_yield = bonds['Yield'].mean()

# Calculate the yield of the bond using the average yield of comparable bonds
bond_yield = ((face_value * coupon_rate) + (face_value - current_price)) / (face_value * years_to_maturity)

# Calculate the bond price using the yield
bond_price = (coupon_rate * face_value) * (1 - (1 + bond_yield) ** (-years_to_maturity)) / bond_yield + face_value * (1 + bond_yield) ** (-years_to_maturity)

print("The bond price using the RVM method is:", round(bond_price, 2))

"""In this example, we define the bond parameters including face value, coupon rate, years to maturity, and current price. We then define comparable bonds using a DataFrame that includes the coupon rate, years to maturity, and price for each bond. We calculate the yield for each comparable bond using the formula (coupon payments + face value - bond price) / (face value * years to maturity). We then calculate the average yield of the comparable bonds and use it to estimate the yield for the bond we want to price. Finally, we use the yield to calculate the bond price using the standard bond pricing formula.

# More about it:


The Relative Value Method (RVM) is an approach used in finance to determine the attractiveness of a particular investment by comparing it to a benchmark. The benchmark could be a market index, another investment or an asset. The idea behind RVM is that it provides a framework for comparing different investments or securities, taking into account their relative value to each other.

The RVM is often used in the analysis of fixed income securities, such as bonds or loans. In this case, the benchmark would typically be a similar bond or loan, with similar characteristics such as credit rating, maturity, and coupon rate. The RVM analysis would compare the yield of the bond being analyzed to the yield of the benchmark bond, with the goal of identifying whether the bond being analyzed is overvalued or undervalued relative to the benchmark.

There are several ways to perform an RVM analysis, but one common method is to calculate the yield spread between the bond being analyzed and the benchmark bond. The yield spread is simply the difference between the yields of the two bonds. If the yield spread is positive, it suggests that the bond being analyzed is offering a higher yield than the benchmark bond, indicating that it may be undervalued. Conversely, if the yield spread is negative, it suggests that the bond being analyzed is offering a lower yield than the benchmark bond, indicating that it may be overvalued.

Another variation of RVM analysis is the credit spread analysis, which compares the yield of a corporate bond to the yield of a Treasury bond with the same maturity. The difference between the two yields is known as the credit spread, and it reflects the additional risk associated with investing in the corporate bond compared to the Treasury bond.

Overall, RVM provides a useful framework for evaluating the relative value of different investments or securities, which can help investors make more informed decisions.
"""