# -*- coding: utf-8 -*-
"""Spot Rate Method.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U3Y5RVY6Q-B-nXueb2zYOyLgX-p6CJQP

The Spot Rate Method is a popular method for pricing bonds. It involves discounting the future cash flows from a bond using spot rates, which are the yields of zero-coupon bonds with the same maturities as the bond's cash flows

The Spot Rate Method is a technique used to determine the value of an investment based on the spot rate curve, which represents the current yield of a set of fixed-income securities with varying maturities. The method is commonly used in the valuation of fixed-income securities such as bonds.

The spot rate is the rate of interest that can be earned on an investment with zero default risk for a specific period of time. The Spot Rate Method assumes that each cash flow from a bond can be treated as a separate zero-coupon bond, each with its own maturity date and corresponding spot rate.

The first step in applying the Spot Rate Method is to determine the spot rates for each of the maturities on the spot rate curve. These spot rates can be obtained from market data or calculated using various mathematical models.

Once the spot rates are determined, the present value of each cash flow from the bond is calculated using the corresponding spot rate for the time period of the cash flow. The sum of these present values gives the current value of the bond.

The Spot Rate Method allows investors to compare the value of bonds with different maturities and coupon rates. It provides a more accurate valuation of a bond than other valuation methods, such as the Yield to Maturity (YTM) method, which assumes that all cash flows are reinvested at a fixed rate.

In summary, the Spot Rate Method is a powerful valuation tool that takes into account the current market rates of interest and provides a more accurate valuation of fixed-income securities. It is widely used by investors, analysts, and traders to make informed investment decisions.
"""

import numpy as np

# Define the yields and maturities of zero-coupon bonds
yields = [0.02, 0.025, 0.03, 0.035, 0.04]
maturities = [1, 2, 3, 4, 5]

# Calculate the spot rates
spot_rates = []
for i in range(1, len(maturities)):
    # Calculate the discount factors
    discount_factors = []
    for j in range(i):
        discount_factors.append(1 / (1 + yields[j]) ** maturities[j])
    # Calculate the spot rate for the current maturity
    spot_rate = ((1 + yields[i]) ** maturities[i] / sum(discount_factors)) ** (1 / maturities[i]) - 1
    spot_rates.append(spot_rate)

print("The spot rates are:", spot_rates)

"""In this code, we first define the bond parameters, including the face value, coupon rate, number of coupon payments, years to maturity, and yield to maturity."""